import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import Main from '../components/Home/Main'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex justify-center items-center'>
        <Main />
     </main>
    </>
  )
}


export async function getServerSideProps() {

  let data = await axios.get(
    `https://api.ipregistry.co/2c0f:f4c0:20c2:4bfc:8c11:18f3:aca:b4f2?key=${process.env.NEXT_PUBLIC_IP_REGISTRY}`
  ).then((res) => {
    return res.data.location.country
  }).catch((err) => console.log(err));

  console.log(data)

return {
  props: {

  }
}
}
